export let englishKeys = [
  tilde = {
    lowerCase: '`',
    upperCase: '~',
    className: 'single symbol',
    row: 'firstRow',
  },
  one = {
    lowerCase: '1',
    upperCase: '!',
    className: 'single numeral',
    row: 'firstRow',
  },
  two = {
    lowerCase: '2',
    upperCase: '@',
    className: 'single numeral',
    row: 'firstRow',
  },
  three = {
    lowerCase: '3',
    upperCase: '#',
    className: 'single numeral',
    row: 'firstRow',
  },
  four = {
    lowerCase: '4',
    upperCase: '$',
    className: 'single numeral',
    row: 'firstRow',
  },
  five = {
    lowerCase: '5',
    upperCase: '%',
    className: 'single numeral',
    row: 'firstRow',
  },
  six = {
    lowerCase: '6',
    upperCase: '^',
    className: 'single numeral',
    row: 'firstRow',
  },
  seven = {
    lowerCase: '7',
    upperCase: '&',
    className: 'single numeral',
    row: 'firstRow',
  },
  eigth = {
    lowerCase: '8',
    upperCase: '*',
    className: 'single numeral',
    row: 'firstRow',
  },
  nine = {
    lowerCase: '9',
    upperCase: '(',
    className: 'single numeral',
    row: 'firstRow',
  },
  zero = {
    lowerCase: '0',
    upperCase: ')',
    className: 'single numeral',
    row: 'firstRow',
  },
  minus = {
    lowerCase: '-',
    upperCase: '_',
    className: 'single numeral',
    row: 'firstRow',
  },
  equally = {
    lowerCase: '=',
    upperCase: '+',
    className: 'single numeral',
    row: 'firstRow',
  },
  backspace = {
    lowerCase: '<-Bacspace',
    upperCase: '<-Bacspace',
    className: 'service backspace',
    row: 'firstRow',
  },
  tab = {
    lowerCase: '---> Tab',
    upperCase: '<--- Tab',
    className: 'service tab',
    row: 'secondRow',
  },
  q = {
    lowerCase: 'q',
    upperCase: 'Q',
    className: 'single letter',
    row: 'secondRow',
  },
  w = {
    lowerCase: 'w',
    upperCase: 'W',
    className: 'single letter',
    row: 'secondRow',
  },
  e = {
    lowerCase: 'e',
    upperCase: 'E',
    className: 'single letter',
    row: 'secondRow',
  },
  r = {
    lowerCase: 'r',
    upperCase: 'R',
    className: 'single letter',
    row: 'secondRow',
  },
  t = {
    lowerCase: 't',
    upperCase: 'T',
    className: 'single letter',
    row: 'secondRow',
  },
  y = {
    lowerCase: 'y',
    upperCase: 'Y',
    className: 'single letter',
    row: 'secondRow',
  },
  u = {
    lowerCase: 'u',
    upperCase: 'U',
    className: 'single letter',
    row: 'secondRow',
  },
  i = {
    lowerCase: 'i',
    upperCase: 'I',
    className: 'single letter',
    row: 'secondRow',
  },
  o = {
    lowerCase: 'o',
    upperCase: 'O',
    className: 'single letter',
    row: 'secondRow',
  },
  p = {
    lowerCase: 'p',
    upperCase: 'P',
    className: 'single letter',
    row: 'secondRow',
  },
  brOpen = {
    lowerCase: '[',
    upperCase: '{',
    className: 'single symbol',
    row: 'secondRow',
  },
  brClose = {
    lowerCase: ']',
    upperCase: '}',
    className: 'single symbol',
    row: 'secondRow',
  },
  backslash = {
    lowerCase: '\\',
    upperCase: '|',
    className: 'single symbol',
    row: 'secondRow',
  },
  del = {
    lowerCase: 'del',
    upperCase: 'del',
    className: 'single service',
    row: 'secondRow',
  },
  caps = {
    lowerCase: 'Caps Lock',
    upperCase: 'Caps Lock',
    className: 'service cupsLock',
    row: 'thirdRow',
  },
  a = {
    lowerCase: 'a',
    upperCase: 'A',
    className: 'single letter',
    row: 'thirdRow',
  },
  s = {
    lowerCase: 's',
    upperCase: 'S',
    className: 'single letter',
    row: 'thirdRow',
  },
  d = {
    lowerCase: 'd',
    upperCase: 'D',
    className: 'single letter',
    row: 'thirdRow',
  },
  f = {
    lowerCase: 'f',
    upperCase: 'F',
    className: 'single letter',
    row: 'thirdRow',
  },
  g = {
    lowerCase: 'g',
    upperCase: 'G',
    className: 'single letter',
    row: 'thirdRow',
  },
  h = {
    lowerCase: 'h',
    upperCase: 'H',
    className: 'single letter',
    row: 'thirdRow',
  },
  j = {
    lowerCase: 'j',
    upperCase: 'J',
    className: 'single letter',
    row: 'thirdRow',
  },
  k = {
    lowerCase: 'k',
    upperCase: 'K',
    className: 'single letter',
    row: 'thirdRow',
  },
  l = {
    lowerCase: 'l',
    upperCase: 'L',
    className: 'single letter',
    row: 'thirdRow',
  },
  semicolon = {
    lowerCase: ';',
    upperCase: ':',
    className: 'single symbol',
    row: 'thirdRow',
  },
  apostrophe = {
    lowerCase: "'",
    upperCase: '"',
    className: 'single symbol',
    row: 'thirdRow',
  },
  enter = {
    lowerCase: 'Enter',
    upperCase: 'Enter',
    className: 'service enter',
    row: 'thirdRow',
  },
  leftShift = {
    lowerCase: 'shift',
    upperCase: 'SHIFT',
    className: 'service shift',
    row: 'fourthRow',
  },
  z = {
    lowerCase: 'z',
    upperCase: 'Z',
    className: 'single letter',
    row: 'fourthRow',
  },
  x = {
    lowerCase: 'x',
    upperCase: 'X',
    className: 'single letter',
    row: 'fourthRow',
  },
  c = {
    lowerCase: 'c',
    upperCase: 'C',
    className: 'single letter',
    row: 'fourthRow',
  },
  v = {
    lowerCase: 'v',
    upperCase: 'V',
    className: 'single letter',
    row: 'fourthRow',
  },
  b = {
    lowerCase: 'b',
    upperCase: 'B',
    className: 'single letter',
    row: 'fourthRow',
  },
  n = {
    lowerCase: 'n',
    upperCase: 'N',
    className: 'single letter',
    row: 'fourthRow',
  },
  m = {
    lowerCase: 'm',
    upperCase: 'M',
    className: 'single letter',
    row: 'fourthRow',
  },
  comma = {
    lowerCase: ',',
    upperCase: '<',
    className: 'single symbol',
    row: 'fourthRow',
  },
  dot = {
    lowerCase: '.',
    upperCase: '>',
    className: 'single symbol',
    row: 'fourthRow',
  },
  slash = {
    lowerCase: '/',
    upperCase: '?',
    className: 'single symbol',
    row: 'fourthRow',
  },
  up = {
    lowerCase: '˄',
    upperCase: '˄',
    className: 'navigation single',
    row: 'fourthRow',
  },
  rightShift = {
    lowerCase: 'shift',
    upperCase: 'SHIFT',
    className: 'service single',
    row: 'fourthRow',
  },
  leftCtrl = {
    lowerCase: 'ctrl',
    upperCase: 'CTRL',
    className: 'service double',
    row: 'fifthRow',
  },
  win = {
    lowerCase: 'win',
    upperCase: 'WIN',
    className: 'service double',
    row: 'fifthRow',
  },
  leftAlt = {
    lowerCase: 'alt',
    upperCase: 'ALT',
    className: 'service double',
    row: 'fifthRow',
  },
  space = {
    lowerCase: ' ',
    upperCase: ' ',
    className: 'service space',
    row: 'fifthRow',
  },
  rightAlt = {
    lowerCase: 'alt',
    upperCase: 'ALT',
    className: 'service double',
    row: 'fifthRow',
  },
  rightCtrl = {
    lowerCase: 'ctrl',
    upperCase: 'CTRL',
    className: 'service double',
    row: 'fifthRow',
  },
  left = {
    lowerCase: '˂',
    upperCase: '˂',
    className: 'navigation single',
    row: 'fifthRow',
  },
  down = {
    lowerCase: '˅',
    upperCase: '˅',
    className: 'navigation single',
    row: 'fifthRow',
  },
  right = {
    lowerCase: '˃',
    upperCase: '˃',
    className: 'navigation single',
    row: 'fifthRow',
  },
];
