let russianKeys = [
  tilde = {
    lowerCase: 'ё',
    upperCase: 'Ё',
    className: 'single symbol',
    row: 'firstRow',
  },
  one = {
    lowerCase: '1',
    upperCase: '!',
    className: 'single numeral',
    row: 'firstRow',
  },
  two = {
    lowerCase: '2',
    upperCase: '"',
    className: 'single numeral',
    row: 'firstRow',
  },
  three = {
    lowerCase: '3',
    upperCase: '№',
    className: 'single numeral',
    row: 'firstRow',
  },
  four = {
    lowerCase: '4',
    upperCase: ';',
    className: 'single numeral',
    row: 'firstRow',
  },
  five = {
    lowerCase: '5',
    upperCase: '%',
    className: 'single numeral',
    row: 'firstRow',
  },
  six = {
    lowerCase: '6',
    upperCase: ':',
    className: 'single numeral',
    row: 'firstRow',
  },
  seven = {
    lowerCase: '7',
    upperCase: '?',
    className: 'single numeral',
    row: 'firstRow',
  },
  eigth = {
    lowerCase: '8',
    upperCase: '*',
    className: 'single numeral',
    row: 'firstRow',
  },
  nine = {
    lowerCase: '9',
    upperCase: '(',
    className: 'single numeral',
    row: 'firstRow',
  },
  zero = {
    lowerCase: '0',
    upperCase: ')',
    className: 'single numeral',
    row: 'firstRow',
  },
  minus = {
    lowerCase: '-',
    upperCase: '_',
    className: 'single numeral',
    row: 'firstRow',
  },
  equally = {
    lowerCase: '=',
    upperCase: '+',
    className: 'single numeral',
    row: 'firstRow',
  },
  backspace = {
    lowerCase: '<-Bacspace',
    upperCase: '<-Bacspace',
    className: 'service backspace',
    row: 'firstRow',
  },
  tab = {
    lowerCase: '---> Tab',
    upperCase: '<--- Tab',
    className: 'service tab',
    row: 'secondRow',
  },
  q = {
    lowerCase: 'й',
    upperCase: 'Й',
    className: 'single letter',
    row: 'secondRow',
  },
  w = {
    lowerCase: 'ц',
    upperCase: 'Ц',
    className: 'single letter',
    row: 'secondRow',
  },
  e = {
    lowerCase: 'у',
    upperCase: 'У',
    className: 'single letter',
    row: 'secondRow',
  },
  r = {
    lowerCase: 'к',
    upperCase: 'К',
    className: 'single letter',
    row: 'secondRow',
  },
  t = {
    lowerCase: 'е',
    upperCase: 'Е',
    className: 'single letter',
    row: 'secondRow',
  },
  y = {
    lowerCase: 'н',
    upperCase: 'Н',
    className: 'single letter',
    row: 'secondRow',
  },
  u = {
    lowerCase: 'г',
    upperCase: 'Г',
    className: 'single letter',
    row: 'secondRow',
  },
  i = {
    lowerCase: 'ш',
    upperCase: 'Ш',
    className: 'single letter',
    row: 'secondRow',
  },
  o = {
    lowerCase: 'щ',
    upperCase: 'Щ',
    className: 'single letter',
    row: 'secondRow',
  },
  p = {
    lowerCase: 'з',
    upperCase: 'З',
    className: 'single letter',
    row: 'secondRow',
  },
  brOpen = {
    lowerCase: 'х',
    upperCase: 'Х',
    className: 'single symbol',
    row: 'secondRow',
  },
  brClose = {
    lowerCase: 'ъ',
    upperCase: 'Ъ',
    className: 'single symbol',
    row: 'secondRow',
  },
  backslash = {
    lowerCase: '\\',
    upperCase: '/',
    className: 'single symbol',
    row: 'secondRow',
  },
  del = {
    lowerCase: 'del',
    upperCase: 'del',
    className: 'single service',
    row: 'secondRow',
  },
  caps = {
    lowerCase: 'Caps Lock',
    upperCase: 'Caps Lock',
    className: 'service cupsLock',
    row: 'thirdRow',
  },
  a = {
    lowerCase: 'ф',
    upperCase: 'Ф',
    className: 'single letter',
    row: 'thirdRow',
  },
  s = {
    lowerCase: 'ы',
    upperCase: 'Ы',
    className: 'single letter',
    row: 'thirdRow',
  },
  d = {
    lowerCase: 'в',
    upperCase: 'В',
    className: 'single letter',
    row: 'thirdRow',
  },
  f = {
    lowerCase: 'а',
    upperCase: 'А',
    className: 'single letter',
    row: 'thirdRow',
  },
  g = {
    lowerCase: 'п',
    upperCase: 'П',
    className: 'single letter',
    row: 'thirdRow',
  },
  h = {
    lowerCase: 'р',
    upperCase: 'Р',
    className: 'single letter',
    row: 'thirdRow',
  },
  j = {
    lowerCase: 'о',
    upperCase: 'О',
    className: 'single letter',
    row: 'thirdRow',
  },
  k = {
    lowerCase: 'л',
    upperCase: 'Л',
    className: 'single letter',
    row: 'thirdRow',
  },
  l = {
    lowerCase: 'д',
    upperCase: 'Д',
    className: 'single letter',
    row: 'thirdRow',
  },
  semicolon = {
    lowerCase: 'ж',
    upperCase: 'Ж',
    className: 'single symbol',
    row: 'thirdRow',
  },
  apostrophe = {
    lowerCase: "э",
    upperCase: 'Э',
    className: 'single symbol',
    row: 'thirdRow',
  },
  enter = {
    lowerCase: 'Enter',
    upperCase: 'Enter',
    className: 'service enter',
    row: 'thirdRow',
  },
  leftShift = {
    lowerCase: 'shift',
    upperCase: 'SHIFT',
    className: 'service shift',
    row: 'fourthRow',
  },
  z = {
    lowerCase: 'я',
    upperCase: 'Я',
    className: 'single letter',
    row: 'fourthRow',
  },
  x = {
    lowerCase: 'ч',
    upperCase: 'Ч',
    className: 'single letter',
    row: 'fourthRow',
  },
  c = {
    lowerCase: 'с',
    upperCase: 'С',
    className: 'single letter',
    row: 'fourthRow',
  },
  v = {
    lowerCase: 'м',
    upperCase: 'М',
    className: 'single letter',
    row: 'fourthRow',
  },
  b = {
    lowerCase: 'и',
    upperCase: 'И',
    className: 'single letter',
    row: 'fourthRow',
  },
  n = {
    lowerCase: 'т',
    upperCase: 'Т',
    className: 'single letter',
    row: 'fourthRow',
  },
  m = {
    lowerCase: 'ь',
    upperCase: 'Ь',
    className: 'single letter',
    row: 'fourthRow',
  },
  comma = {
    lowerCase: 'б',
    upperCase: 'Б',
    className: 'single symbol',
    row: 'fourthRow',
  },
  dot = {
    lowerCase: 'ю',
    upperCase: 'Ю',
    className: 'single symbol',
    row: 'fourthRow',
  },
  slash = {
    lowerCase: '.',
    upperCase: ',',
    className: 'single symbol',
    row: 'fourthRow',
  },
  up = {
    lowerCase: '˄',
    upperCase: '˄',
    className: 'navigation single',
    row: 'fourthRow',
  },
  rightShift = {
    lowerCase: 'shift',
    upperCase: 'SHIFT',
    className: 'service single',
    row: 'fourthRow',
  },
  leftCtrl = {
    lowerCase: 'ctrl',
    upperCase: 'CTRL',
    className: 'service double',
    row: 'fifthRow',
  },
  win = {
    lowerCase: 'win',
    upperCase: 'WIN',
    className: 'service double',
    row: 'fifthRow',
  },
  leftAlt = {
    lowerCase: 'alt',
    upperCase: 'ALT',
    className: 'service double',
    row: 'fifthRow',
  },
  space = {
    lowerCase: ' ',
    upperCase: ' ',
    className: 'service space',
    row: 'fifthRow',
  },
  rightAlt = {
    lowerCase: 'alt',
    upperCase: 'ALT',
    className: 'service double',
    row: 'fifthRow',
  },
  rightCtrl = {
    lowerCase: 'ctrl',
    upperCase: 'CTRL',
    className: 'service double',
    row: 'fifthRow',
  },
  left = {
    lowerCase: '˂',
    upperCase: '˂',
    className: 'navigation single',
    row: 'fifthRow',
  },
  down = {
    lowerCase: '˅',
    upperCase: '˅',
    className: 'navigation single',
    row: 'fifthRow',
  },
  right = {
    lowerCase: '˃',
    upperCase: '˃',
    className: 'navigation single',
    row: 'fifthRow',
  },
];
